### ISSUE TITLE
Automatically discover clusterName

### ISSUE THREAD

**Issue by rvangsgaard** [devantler/ksail#209]
### Description

Try to discover clusterName based on current folder name. Consider validating the discovered name by looking for a corresponding YAML-file.

Example:
1. CWD=$(current work dir)
2. Check for file with name $CWD-k3d-config.yaml

**Comment by rvangsgaard** [comment]
> I do not want to enforce ways of working, so do you have a suggestion of how I could handle if there are multiple KSail clusters initialized in the same folder?

I think a good default behavior is a good thing, and allow the user to override it. In this case:
1. If the user specifies a cluster name, user it.
2. If not, look for a config file (cluster) with the same name as the folder.

**Comment by rvangsgaard** [comment]
I do not understand the proposed solution - will the ksail native config file only contain exactly one clusterName or multiple. If you can, please elaborate on the ksail native config file, especially the example.

**Comment by devantler** [comment]
It will contain one cluster name.

See it as a per-project configuration. One project should not need more than one ksail project. In rare cases where there could be more than one ksail cluster in a folder, the configuration will use the cluster name to infer which one to provision when running:

`ksail up`
