### ISSUE TITLE
Checking that docker is running fails on MAC if docker.sock is not enabled

### ISSUE THREAD

**Issue by AlmiS** [devantler/ksail#210]
### Description of the bug

For Ksail to detect propperly that the docker daemon is running, MAC needs to be configured to have the docker.sock enabled.

To allow Ksail to talk with docker the user must enable the docker.sock See attached image. Somehow this needs to be documented or somehow ksail should help the user to know what to do.

<img width="960" alt="Screenshot 2024-02-28 at 11 21 19" src="https://github.com/devantler/ksail/assets/8699062/77844e60-5083-47a3-8ca6-185761260a4b">

**Comment by devantler** [comment]
Thanks for reporting this issue.

My go-to solution would be to:

1. Document this in the README as a prerequisite for running KSail.
2. Guide the user to enable the option in the "Checking if Docker is running" step if they are running KSail from a Mac, and the Docker client is unable to access the Docker Socket for unknown reasons.
